### PR TITLE
Install React as dev dependencies

### PR DESCRIPTION
**Pull request by eatyourgreens**
Install react, react-dom and prop-types as dev dependencies.

### CODE REVIEW

**Review by srallen — CHANGES_REQUESTED** [review]
I'm getting compiling errors when installing this branch with the React 16 upgrade branch. I'm not sure what's going on yet. 

As an aside, would declaring these as peer dependencies be more appropriate? It'll accomplish the same in that it won't install those itself, but then it will at least warn on install if the versions don't match and let us know if the react version here needs updating.

**Comment by eatyourgreens** [comment]
I thought npm dropped peer dependencies? I'll double check that.

No problems here installing this branch to a local copy of the React 16 branch of PFE.

**Comment by srallen** [comment]
@eatyourgreens It's still supported. What changed is that new versions of npm do not automatically install peer dependencies if they aren't declared in the package.json of the dependent.

**Comment by srallen** [comment]
The install works ok, but I'm seeing compiling failures when running the app.

**Comment by eatyourgreens** [comment]
I had PFE running locally with this branch earlier. I'll take another look. It might be that Seven-Ten-Client needs some changes to work with React 16.

**Comment by eatyourgreens** [comment]
Wait, I'm an idiot. This can't be installed directly from github. It has to be built first.

**Comment by srallen** [comment]
Doh, I missed that too then. I'll try that locally with npm link

**Comment by eatyourgreens** [comment]
I'm going to try updating it to React 16 and see if the tests still run. In theory, it should be ok but I haven't tested it.

**Comment by eatyourgreens** [comment]
Tests still pass on this branch with React 16.3, so it should be compatible with 15 or 16.

**Comment by srallen** [comment]
I tried again with building locally and using npm link and it works.

**Review by srallen — APPROVED** [review]
This is working, but maybe a peer dep might be better.

**Comment by eatyourgreens** [comment]
Published as 3.3.0.

**Pull request merged**
